### Get All Contacts
https://localhost:5001/contacts

<> 2020-05-28T043742.200.json

### Get Existing Contact
https://localhost:5001/contacts/1

<> 2020-05-28T043742-1.200.json

### Get non existing Contact
https://localhost:5001/contacts/99999999

### Save Valid Contact
POST https://localhost:5001/contacts
Content-Type: application/json

{
  "FirstName": "Deidre",
  "LastName" : "Guadagno",
  "MiddleName" : "Ann",
  "EmailAddress" : "dontmail@example.com"
}

<> 2020-05-28T045658.201.json


### Save Valid Contact with address and phone number
POST https://localhost:5001/contacts
Content-Type: application/json

{
  "FirstName": "Jane",
  "LastName" : "Alice",
  "MiddleName" : "Doe",
  "EmailAddress" : "jane.a.doe@example.com",
  "Phones": [
    {
      "phonenumber": "8675309",
      "extension": ""
    },
    {
      "phonenumber": "5551212",
      "extension": "12345"
    }
  ],
  "Addresses": [
    {
      "StreetAddress": "123 Main Street",
      "SecondaryAddress": "2nd Floor",
      "Unit": "all",
      "City": "Chandler",
      "State": "AZ",
      "Country": "US",
      "PostalCode": "85248"
    }
  ]
}

### Save Invalid Contact
POST https://localhost:5001/contacts
Content-Type: application/json

{
  "FirstName": "",
  "LastName" : "Guadagno",
  "MiddleName" : "Hector",
  "EmailAddress" : "dontmail@example.com"
}

<> 2020-05-28T045910.500.txt

### Delete Contact
DELETE https://localhost:5001/contacts/34

### Search for contacts
GET https://localhost:5001/contacts/search?firstname=Joseph&lastname=Guadagno

### Search for Contact
GET https://localhost:5001/contacts/search?firstname=Deidre&lastname=Guadagno


### Get the phones for Contact
GET https://localhost:5001/contacts/37/phones

### Get the phone by phone id for Contact
GET https://localhost:5001/contacts/37/phones/1

### Get the addresses for Contact
GET https://localhost:5001/contacts/37/addresses

### Get the address by id for Contact
GET https://localhost:5001/contacts/37/addresses/1